version: '3.3'

services:
  mssql:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "password123"
    ports:
      - 1433:1433
    volumes:
      - my-volume:/var/opt/mssql

volumes:
  my-volume:
